ShiftDiary.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShiftDiary.Web.Controllers
{
    public class BaseController : Controller
    {
        //
        // GET: /Base/

        private ActionResult Index()
        {
            return View();
        }

        public void ReturnUrlSet()
        {
            if (HttpContext.Request.UrlReferrer != null)
            {
                TempData["ReturnUrl"] = HttpContext.Request.UrlReferrer.OriginalString;
            }
            else
            {
                TempData["ReturnUrl"] = String.Empty;
            }
        }

        public bool RequestValid()
        {
            return true;
        }
    }
}

ShiftDiary.Web/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShiftDiary.DTO;
using ShiftDiary.Web.ShiftService;

namespace ShiftDiary.Web.Controllers
{
    public class CalendarController : BaseController
    {
        private IShiftService shiftService;

        public CalendarController(IShiftService shiftService)
        {
            this.shiftService = shiftService;
        }

        //
        // GET: /Calendar/

        public ActionResult Index()
        {
            DateTime now = DateTime.Now;
            return View("Index", GenerateCalendarData(now));
        }

        //
        // GET: /Calendar/Month
        public ActionResult GotoMonth(int gotoMonth, int gotoYear)
        {
            DateTime date = new DateTime(gotoYear, gotoMonth, 1);
            return View("Index", GenerateCalendarData(date));
        }

        public Month GenerateCalendarData(DateTime now)
        {
            ViewBag.CurrentMonth = now.ToString("MMMM");
            ViewBag.CurrentMonthInt = now.ToString("MM");
            ViewBag.CurrentYear = now.ToString("yyyy");

            ViewBag.NextMonth = new DateTime(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt), 1).AddMonths(1).Month;
            ViewBag.PrevMonth = new DateTime(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt), 1).AddMonths(-1).Month;

            ViewBag.NextYear = new DateTime(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt), 1).AddMonths(1).Year;
            ViewBag.PrevYear = new DateTime(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt), 1).AddMonths(-1).Year;

            Week week = new Week();
            Month month = new Month(int.Parse(ViewBag.CurrentMonthInt), ViewBag.CurrentMonth, int.Parse(ViewBag.CurrentYear));

            for (int i = 1; i <= DateTime.DaysInMonth(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt)); i++)
            {
                DateTime dt = new DateTime(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt), i);
                Day day = new Day(dt);
                day.Shifts = shiftService.GetShiftForDay(day).ToList();

                week.Days.Add(day);

                if (dt.DayOfWeek == DayOfWeek.Sunday || i == DateTime.DaysInMonth(int.Parse(ViewBag.CurrentYear), int.Parse(ViewBag.CurrentMonthInt)))
                {
                    month.Weeks.Add(week);
                    week = new Week();
                }
            }            

            ViewBag.WeekDayCount = 0;

            return month;
        }

        public ActionResult ShiftDetails()
        {
            return View("ShiftDetails");
        }
    }
}

ShiftDiary.Web/Views/Calendar/Index.cshtml
@using ShiftDiary.DTO;
@model Month
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>@ViewBag.Title</title>
    <link href="../../Content/css/ui-lightness/jquery-ui-1.9.2.custom.min.css" rel="Stylesheet" />
    <script src="../../Content/scripts/jquery-1.8.3.min.js" type="text/javascript"></script>
    <script src="../../Content/scripts/jquery-ui-1.9.2.custom.min.js" type="text/javascript"></script>
</head>
<body id="main_page">
    <div style="text-align: center;">
        <table width="1400px">
            <thead>
                <tr>
                    <td align="left" style="width: 200px;">
                        <h1>@Html.ActionLink("<<", "GotoMonth", "Calendar", new { gotoMonth = @ViewBag.PrevMonth, gotoYear = @ViewBag.PrevYear }, null)</h1>
                    </td>
                    <td style="width: 1000px;" colspan="5" align="center">
                        <h1>
                            @ViewBag.CurrentMonth &nbsp;&nbsp;&nbsp;&nbsp;@ViewBag.CurrentYear
                        </h1>
                    </td>
                    <td style="width: 200px;" align="right">
                        <h1>@Html.ActionLink(">>", "GotoMonth", "Calendar", new { gotoMonth = @ViewBag.NextMonth, gotoYear = @ViewBag.NextYear }, null)</h1>
                    </td>
                </tr>
                <tr>
                    <td style="width: 200px;" align="center">
                        Monday
                    </td>
                    <td style="width: 200px;" align="center">
                        Tuesday
                    </td>
                    <td style="width: 200px;" align="center">
                        Wednesday
                    </td>
                    <td style="width: 200px;" align="center">
                        Thursday
                    </td>
                    <td style="width: 200px;" align="center">
                        Friday
                    </td>
                    <td style="width: 200px;" align="center">
                        Saturday
                    </td>
                    <td style="width: 200px;" align="center">
                        Sunday
                    </td>
                </tr>
            </thead>
            <tbody>
                @foreach (Week week in Model.Weeks)
            {
                    <tr>
                        @{
                        ViewBag.WeekDayCount = 0;
                        }
                        @for (int i = 0; i < 7; i++)
                    {
                        if (i == 0 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Monday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });                            
                            ViewBag.WeekDayCount++;
                        }
                        else if(i ==0)
                        {
                            <td>
                            </td>
                        }
                        
                        if (i == 1 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Tuesday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });
                            ViewBag.WeekDayCount++;
                        }
                        else if(i == 1)
                        {
                            <td>
                            </td>
                        }

                        if (i == 2 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Wednesday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });
                            ViewBag.WeekDayCount++;
                        }
                        else if (i == 2)
                        {
                            <td>
                            </td>
                        }

                        if (i == 3 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Thursday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });    
                            ViewBag.WeekDayCount++;
                        }
                        else if (i == 3)
                        {
                            <td>
                            </td>
                        }


                        if (i == 4 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Friday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });
                            ViewBag.WeekDayCount++;
                        }
                        else if (i == 4)
                        {
                            <td>
                            </td>
                        }

                        if (i == 5 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Saturday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });
                            ViewBag.WeekDayCount++;
                        }
                        else if (i == 5)
                        {
                            <td align="center">
                            </td>
                        }

                        if (i == 6 && week.Days.Count > ViewBag.WeekDayCount && week.Days[ViewBag.WeekDayCount].Date.DayOfWeek == DayOfWeek.Sunday)
                        {
                            @RenderPage("~/Views/Shared/CalendarCell.cshtml", new { week = week });
                            ViewBag.WeekDayCount++;
                        }
                        else if (i == 6)
                        {
                            <td>
                            </td>
                        }
                    }
                    </tr>
            }
            </tbody>
        </table>
    </div>
    <div>
    </div>
    <script type="text/javascript">

        $.ajaxSetup({ cache: false });

        $(document).ready(function ()
        {
            $(".shiftName").live("click", function (e)
            {
                e.preventDefault();

                $("<div></div>")
            .addClass("dialog")
            .attr("id", $(this)
            .attr("shift_id"))
            .appendTo("body")
            .dialog({
                title: $(this).attr("shift_name"),
                close: function () { $(this).remove(); },
                modal: true,
                height: 250,
                width: 400,
                left: 0

            })
            .load(this.href);
                    });

            $(".close").live("click", function (e)
            {
                e.preventDefault();
                $(this).closest(".dialog").dialog("close");
            });
        });
    </script>
</body>
</html>

ShiftDiary.Web/Views/Calendar/ShiftDetails.cshtml
@{
    ViewBag.Title = "About Us";
    Layout = null;
}
<h2>
    About</h2>
<p>
    Hello, this is a modal jquery popup !
</p>
<p>
<a href="javascript:void(0);" class="close">Close this Window</a></p>

ShiftDiary.Web/Views/Shared/BookingSection.cshtml
@using HotelManagement.Helpers;

<div class="box maxheight">
    <div class="inner">
        <h3>@Html.AppSetting("BookingHeaderText")</h3>
        <form action="" id="reservation-form" class="userform">
        <fieldset>
            <div class="field">
                <label>
                    @Html.AppSetting("CheckInHeaderText")</label><select id="arrDay" class="select1"><option>30</option>
                    </select><select id="arrMonth" class="select2">
                    </select></div>
            <div class="field">
                <label>
                    @Html.AppSetting("CheckOutHeaderText")</label><select id="depDay" class="select1"><option>01</option>
                    </select><select id="depMonth" class="select2">
                    </select></div>
            <div class="field">
                Persons: &nbsp;<input type="text" value="1" />&nbsp; &nbsp; &nbsp; &nbsp; Rooms:&nbsp;
                <input type="text" value="1" /></div>
            <div class="button">
                <span><span><a href="#" onclick="document.getElementById('reservationm-form').submit()">Check Availability</a></span></span></div>
        </fieldset>
        </form>
    </div>
</div>

<script type="text/javascript">

    function populateBookingMonths()
    {
        $.ajaxSetup({ "async": false });
        $.getJSON('/Booking/BookingMonths', function (data)
        {
            var options = $(".select2");
            $.each(data, function ()
            {
                options.append($("<option />").val(this).text(this));
            });
        });        
    }

    function populateArrDays()
    {
        var selectedVal;
        $('#arrMonth option:selected').each(function ()
        {
            selectedVal = $(this).text();
        });

        $('#arrDay option').remove();

        $.getJSON('/Booking/BookingDays', { month: selectedVal }, function (data)
        {
            var options = $("#arrDay");
            $.each(data, function ()
            {
                options.append($("<option />").val(this).text(this));
            });
        });
    }

    $(function ()
    {
        $('#arrMonth').change(function ()
        {
            populateArrDays();            
        });

        populateBookingMonths();
    });   

</script>

ShiftDiary.Web/Views/Shared/CalendarCell.cshtml
@using ShiftDiary.DTO;

<td align="center" style="height: 150px;" valign="top">
    <table>
        <tr>
            <td>
                <h1>@Page.week.Days[ViewBag.WeekDayCount].Date.Day</h1>
            </td>
        </tr>
        @foreach (Shift shift in @Page.week.Days[ViewBag.WeekDayCount].Shifts)
        {
            <tr>
                <td>
                    <div>
                        <img height="20px" width="20px" src=@shift.GemUrl />
                        @Html.ActionLink(@shift.Name, "ShiftDetails", null, new {@class = "shiftName", shift_id = @shift.Id, shift_name = @shift.Name })
                    </div>
                </td>
            </tr>
        }
    </table>
</td>

ShiftDiary.Web/Views/Shared/Header.cshtml
@using ShiftDiary.Helpers;

<h1>@AppCache.AppSettings.HeaderText</h1>


ShiftDiary.Web/Views/Shared/LoginInfo.cshtml
@using HotelManagement.Helpers.CacheHelpers

@if (SessionCache.UserId == null)
{
    <span class="login">
        @Html.ActionLink("Login", "Index", "Login")
    </span>
}
else
{ 
    <span class="login">
        @Html.ActionLink(SessionCache.UserEmail + " ", "Logout", "Login", new { title = "Click for Account Details" })<br />        
        @Html.ActionLink("Logout", "Logout", "Login", null, new { title = "Click to Logout" })
    </span>
}

ShiftDiary.Web/Views/Shared/MainMenu.cshtml
@using ShiftDiary.Helpers;
@using ShiftDiary.Helpers.CacheHelpers;
@using ShiftDiary.DTO;

<div class="inner">
    <ul class="nav">
        @if (SessionCache.UserId == null)
        { 
            <li>@Html.ActionLink("Home Page", "Index", "Home")</li>
            <li>@Html.ActionLink("Hotel Chains", "Index", "HotelChain")</li>
            <li>@Html.ActionLink("Hotels", "Index", "Hotel")</li>
            <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
            <li><a href="testimonials.html">Testimonials</a></li>
            <li><a href="booking.html">Booking</a></li>
        }
        else
        {
            foreach (MenuDTO menu in SessionCache.UserMenus)
            { 
                <li>@Html.ActionLink(menu.Description, menu.Action, menu.Controller, new { title = menu.Tooltip })</li>
            }
        }
    </ul>
</div>
